name: build

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.runner.name }}
    runs-on: ${{ matrix.runner.os }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - { name: amd64, os: ubuntu-24.04 }
          - { name: arm64, os: ubuntu-24.04-arm }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache mavlink-router builddir
        uses: actions/cache@v4
        with:
          path: build/mavlink-router
          key: ${{ runner.os }}-mavrouter-${{ hashFiles('thirdparty/mavlink-router/**') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            meson \
            ninja-build \
            libtool \
            libtool-bin
          libtool --version

      - name: Build project
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload mavlink-routerd
        uses: actions/upload-artifact@v4
        with:
          name: mavlink-routerd-${{ matrix.runner.name }}
          path: build/bin/mavlink-routerd
